### PR TITLE
Add inline reply feature

### PR DESCRIPTION
**Pull request by clansty**
Add the inline reply feature.

Tested on KDE Plasma 5.22.4

ref: <https://github.com/KDE/knotifications/blob/master/src/notifybypopup.cpp>

image
image

### CODE REVIEW

**Comment by cronvel** [comment]
Hi @Clansty,

I'm glad you found my lib helpful.
Do you know if this inline reply feature is widely supported?
It doesn't seem supported on Gnome desktop (but the support of freedesktop notifications has always been crappy on Gnome).
Is it supported by other desktops?

**Comment by clansty** [comment]
It is supported by KDE Plasma.

But according to what I've learnt, only a few DEs support the inline reply capability

**Comment by cronvel** [comment]
Ok thanks @Clansty, I will merge the feature, but I will probably ping you in the future if a user has some trouble with it, since I can't check it by myself! ;)

**Comment by clansty** [comment]
Ok, no problem.

**Comment by cronvel** [comment]
@Clansty Ok it's published as v2.1.0, thanks for your contrib, and good job for mimic'ing my coding style! ;)

**Pull request merged**
